- id: doi:10.1101/2023.05.12.540520

#
- id: doi:10.1073/pnas.2309244121
  type: paper
  image: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMwAAADACAMAAAB/Pny7AAAAllBMVEX///8kHiABdcwAAAD+//1Sl9Cuy+Pd6/QAb8kAc8wHd8ghHyAjHyD5+fm3trcKAAB/fHxmZma+v78QDQ9zc3MQBws/OjuVlJUbFRfz8/Ofn58YEBPKysvc3NwcGhvp6elEQUMAY8DT09NdXV0tKyyHh4epqKhJSEhUVFTq9Pet0OJJjsc2MTI8PTwVFRUkJSQAW7oAaLxietE6AAAIRUlEQVR4nO2aa5urphaA9TBn9mmDl0SNxAvaGGPaGqf9/3+uGAFRgcy00+fsadf77A8zW0RegQULx3EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwIyn42nhZ3W943HPm1YV/jVN2zbNrn5RPS/vOEWz1xDHqV9uC6f8cnPW1hXL+wvD086ySGMqIkyucVP3LkmCICFuX9/2rf9UyEeRFnq537K1T8wLJxfti+1FXehgeFoqn4b2J0uryrB+i3JCXA4hUUTe6lj/EhWZnR5K85zulzohL+wGta6uY87vNcmUt0jWjzQ9zzm1u2igO+zO4LFFhAyGMfFEZqopQKn6AqWMi+I/I3NVHsZqMMybc43o3IRZZvw9QZlVxrWCGuUNhsH8/5pKjzm/GOhlqn2i1myYAsVlfoq7liK1ba49k3FRN9soMmS3bfAxx1YZP1hUHGoLlZ3SIowf42AmCW1h8JkMxugmX6Ei40b3zfB90jNVvHgWRrp2eWohFssQI0lEJCAX3+Iyy2CCZgLCLKbXvMPzK1Rl3KRZj5MnMgWl4gVNMrrhXyDMy7AGXZq4bdswbo4JirD2mXoZ0mXXbCJt4zu7WXYwEuN0IePm4apmu8ypRY8KxVx2Sa/pGhbvxousTNSnh7LyHO9UlYWf3hBi7yK1ucwyyRz42e1nv0ZSJr9pZShNl2uFXaakU7TFNOI1J9dNoQrtuMzQnVVXrzykCN3N8dwkM1UbIxlG6Fknw4LAcgRbZbyUvx182UdTzcNt0zW+lNmuQ14Z7q0uZhnHa+RUHFqtjEvoIgjYZSI6yUStmBf0sikXCpmg0TTWs+0arDLOScqIcbaWwdGbepNV5ipqQ6eqJ+KZ61J7LuMi++z4sIzTzsGh0sqwwVArI8W6ziAh0DieECPH9RIoZQLdFuOvyBykDF9TtjI7dV9j6xlZF2JVnS/cLGhXxWIhQ+m7Nv3vlzlLmb7QyrAoi9EckmwyNb+Wu84jSk/3591q5RVRgo3gpnxHzvN+mcokgzGVS5uyq7TInBGP85P7gW+KcbCaGiw2iBia3K/nD/aOTaY0yexoJ+M2Hnrxdi0ye762EPx4Stnw35NmGYG9gMp+J+gYZoeP9I9NxjfNGYxSGRzwLhINMsuc3+gySGUR3wxHq4UznbdmeDcgdGxClvS+U8gm04gd+zqaMZnTDYlH7ijf15hlwgFzGd6LRTfwjCleDqWql2nCY/s/5s2XW5weniwxdhmPjV9R7bBeZ9gLLvtoHhCpZ5Upax69UCweEgYijK+icxEMeLntd0mekL4Ln5wa2GTYmimH75BuZZirTNFp4k8yhnUmFSXnYOGLhROFq+f6CK1kHkIk361Dn01mOTAPiMgq3yqNjJoKkaRwzD1T3Xgn5nOid2pEYbRu4rmbX+OCHMX2yaPIVCdJeT0iKt9PIhbGpYyXzgMtupRmmUy0TVmTnEzcitp1C73sTnLZ7Spq2muTcXEtOLL0LBfZGVtTBjFHlzJOFYqY5D7y0eOglani6TZMjkonVHc59raryena3GmgEQpuNhtlrOQS5W42Gef3uZKZlwv3kdLXoqeWMv7bo1GsonZx1BMtK1txTuNbn6NkJbSZYgYZF/N/6nGIS5WDh7WMU9wHWRj5nbZn5N5lteMvRWkS6dvnlX4WNv04SmYINh0wOs8PNHL1dW5kxn2J7ELai58XMueeTOOV9mGWKsg9BNpmnLPQ4dp2SNkTLrv3nTJTpo52V2V6bmVYmsK2Z1ObXNmlqown13RME6Qin0TezC+bcSr9PSJ81d0RS+psksGPU0cUF2qo0chMp5yrm1WZstfGpcWTkPUAyRmP0S8Dl9kh8+KpkcHjWRDbDY8qyy7VyXjddo1TZFgihtcP2MiQ+okMi+Q7KmTM5rMMQUv2/mZw6mScKhnWzVVkqj537YxjYHi6Vama6AMypLv6kkK/T9XKsEyBbYkXPorM4dExGGNz/7Br+Xx84RlymPgjMsmTrYJZ5pFqLYbaLON1+dSE8YPEFjkqetk1Gd2OCGfRM+bYbEsB3ivjZXT5NWWW4Ttv5vJWH9fc64u4IxeL2akP0F7z0e/a8zlDc/N28zNkxn0N1ffMLeEyqC00yLCdi23K2B6m4y8z5pPf8Z0TSwXNufSnyDglS4t1MqXM4JC29upIeI9SXmP9GE0By5ivbOY+9r5V4beXiK8zGGXm6fA5MmzbHulk9vKASX+wKldUkXsX4qiJxVbaNXEchvG+TubUKbIlNZ8k4xwuytooZCppaPqCWfDbWHx47GnYaJIbcTpEaPw+E6mrbv6uz4B/UcbJlK4RMi3P53F+NNRYhSJCoPEwYOwYGUqw+PypuMx5998q4yifvLiMkrIY14Yrz3UwJYdxVUI7LBcljNWfRyfUWBv5eTJOF6xkZOpPBmPdpTwCYtthjy0nKKHbzd7US0T7jfvvkXGwaNckc7rJNN8SgVJRJ2ELyAsLJfvxjwC2MnQg2y8gG5lkwv4nExOxLKyVKXHALz+eeqWBKG45Zi1qWSnPVMr0dsRJMv+BBsnzhPadberzuvYxJ3suk4mysT6dOojLxbJ0aqnam4vJb6TeOQv3t/FPZ3KmhPuu2afFh4/RvyNOZeFPX4yv/kcP0AEAAIDvhpeX/3cLPoqlxT9/+3L8bNT85df/fjF+/cXUNS+vv/3vi/Hbq1nmpx//87X4CWS+U0Dme+XfI8Ou//BlsMo4r7//+MX4/dXk4nx7/XJ8M8r8o3j5gvw7ZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgn8kfAWLzxNAy14QAAAAASUVORK5CYII=

- id: doi:10.1101/2024.03.01.582956
  type: preprint
  image: https://s3-us-west-2.amazonaws.com/cbi-image-service-prd/modified/921bc0af-ca29-46d9-b935-2f9bfdcc5539.png

  - id: doi:10.1101/2023.05.12.540520
  type: preprint
  image: https://s3-us-west-2.amazonaws.com/cbi-image-service-prd/modified/921bc0af-ca29-46d9-b935-2f9bfdcc5539.png
  
  - id: doi:10.1111/tpj.16149
  type: paper
  image: https://www.google.com/url?sa=i&url=https%3A%2F%2Ftwitter.com%2Ftheplantjournal&psig=AOvVaw0QNMGA0rjGPMNnKz86AFZi&ust=1720642213332000&source=images&cd=vfe&opi=89978449&ved=0CA8QjRxqFwoTCLCjl_HhmocDFQAAAAAdAAAAABAE

  - id: doi:10.1111/tpj.15882
  type: paper
  image: https://www.google.com/url?sa=i&url=https%3A%2F%2Ftwitter.com%2Ftheplantjournal&psig=AOvVaw0QNMGA0rjGPMNnKz86AFZi&ust=1720642213332000&source=images&cd=vfe&opi=89978449&ved=0CA8QjRxqFwoTCLCjl_HhmocDFQAAAAAdAAAAABAE

  - id: doi:10.1101/2022.01.18.476797
  type: preprint
  image: https://s3-us-west-2.amazonaws.com/cbi-image-service-prd/modified/921bc0af-ca29-46d9-b935-2f9bfdcc5539.png

  - id: doi:10.1111/tpj.15064
  type: paper
  image: https://www.google.com/url?sa=i&url=https%3A%2F%2Ftwitter.com%2Ftheplantjournal&psig=AOvVaw0QNMGA0rjGPMNnKz86AFZi&ust=1720642213332000&source=images&cd=vfe&opi=89978449&ved=0CA8QjRxqFwoTCLCjl_HhmocDFQAAAAAdAAAAABAE

  - id: doi:10.1111/tpj.15064
  type: paper
  image: https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.medigraphic.com%2Fbioquimia%2Fbioquimia%2Fe1-bqgral.htm&psig=AOvVaw1KnW6wQGASqdQLC7Y-3w9s&ust=1720642399482000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCKjMlcrimocDFQAAAAAdAAAAABAE

  - id: doi:10.1080/15592324.2017.1284724
  type: paper
  image: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSaftKGyKJxrwG6bi69jruLWziSy7ETTCDiIw&s

  - id: doi:10.1093/jxb/erw380
  type: paper
  image: https://www.google.com/url?sa=i&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FJournal_of_Experimental_Botany&psig=AOvVaw18-jVJ9PHBmUlK9UwhTnTf&ust=1720642536360000&source=images&cd=vfe&opi=89978449&ved=0CA8QjRxqFwoTCMDvi47jmocDFQAAAAAdAAAAABAE

  - id: doi:10.1038/srep02910
  type: paper
  image: https://www.google.com/url?sa=i&url=https%3A%2F%2Fbionics-group.com%2Favailable-online-open-source-scientific-reports-nature-research%2F&psig=AOvVaw30NxuYZ3cK1Y0U03FCPgDr&ust=1720642608802000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCOitgq7jmocDFQAAAAAdAAAAABAE

  - id: doi:10.1007/s00425-012-1693-z
  type: paper
  image: https://pbs.twimg.com/profile_images/1735255692741668865/0p1K4I5H_400x400.jpg

  - id: doi:10.1364/SENSORS.2012.SW4C.5
  type: paper
  image: https://opg.optica.org/images/conf_papers_thumbnail.jpg
  
