- id: doi:10.1007/s11103-024-01498-x
  type: paper
  image: https://www.califesciences.org/wp-content/uploads/2021/11/Springer-Nature-1.png

- id: doi:10.1073/pnas.2309244121
  type: paper
  image: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLKs19_ZDAqr502IhlAIVSJS_Tp9pvl80Aaw&s

- id: doi:10.1101/2024.03.01.582956
  type: Preprint
  image: https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/BioRxiv_logo.png/220px-BioRxiv_logo.png

- id: doi:10.1101/2023.05.12.540520
  type: Preprint
  image: https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/BioRxiv_logo.png/220px-BioRxiv_logo.png
  
- id: doi:10.1111/tpj.16149
  type: paper
  image: https://retractionwatch.com/wp-content/uploads/2018/10/TPJ_Avatar_400x400.png
  
- id: doi:10.1111/tpj.15882
  type: paper
  image: https://retractionwatch.com/wp-content/uploads/2018/10/TPJ_Avatar_400x400.png
  
- id: doi:10.1101/2022.01.18.476797
  type: Preprint
  image: https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/BioRxiv_logo.png/220px-BioRxiv_logo.png

- id: issn:0185-5751
  type: paper
  date: 2009-01-01
  authors: Nakamura-López Y, Esparza-Aguilar ML, Garrido-Olvera L, Palomar-Olguín VM, Gallardo-Pérez JC
  image: https://www.medigraphic.com/images/cabezales/bioquimia-cbz.gif

- id: doi:10.1111/tpj.15064
  type: paper
  image: https://retractionwatch.com/wp-content/uploads/2018/10/TPJ_Avatar_400x400.png
  
- id: doi:10.1080/15592324.2017.1284724
  type: paper
  image: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSaftKGyKJxrwG6bi69jruLWziSy7ETTCDiIw&s

- id: doi:10.1093/jxb/erw380
  type: paper
  image: https://upload.wikimedia.org/wikipedia/en/8/88/Journal_of_Experimental_Botany.png
  
- id: doi:10.1038/srep02910
  type: paper
  image: https://bionics-group.com/wp-content/uploads/2021/01/Sci-Reports-Nature.jpg
  
- id: doi:10.1007/s00425-012-1693-z
  type: paper
  image: https://pbs.twimg.com/profile_images/1735255692741668865/0p1K4I5H_400x400.jpg

- id: doi:10.1364/sensors.2012.sw4c.5
  type: paper
  image: https://opg.optica.org/images/conf_papers_thumbnail.jpg

  
