- title: Plavisto (Plastid-genome Visualization Tool)
  authors:
    - Andrzej T. Wierzbicki
    - V. Miguel Palomar (collaborator)
  publisher: online
  date: 2022-01-01
  link: plavisto.mcdb.lsa.umich.edu
