- id: doi:10.1101/2023.05.12.540520
  type: paper
  description: Transcription-directed membrane association organizes the chloroplast nucleoid structure
  date: 2023-13-5
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: 
      link: 
    - type: 
      text: 
      link: 
    - type: 
      link: 
  tags:
    - open science
    - collaboration
  repo: 
  group: highlighted
